global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@nordlayer.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://backend:8000/api/v1/webhooks/alerts'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@nordlayer.com'
    subject: '[CRITICAL] NordLayer Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}
  webhook_configs:
  - url: 'http://backend:8000/api/v1/webhooks/alerts'
    send_resolved: true
  # Telegram notifications for critical alerts
  webhook_configs:
  - url: 'http://telegram-bot:8001/webhook/alerts'
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'admin@nordlayer.com'
    subject: '[WARNING] NordLayer Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']