name: Deploy via Webhook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger deployment webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' \
          "http://${{ secrets.SERVER_HOST }}:9000/hooks/deploy"